# Use this only if SIM is enabled
#metricPrefix: "Custom Metrics|Amazon Elasticsearch|"

# If SIM is not enabled, then use this
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Amazon Elasticsearch|"
#To find the <COMPONENT_ID> in your environment,
#please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java

# awsAccessKey, awsSecretKey, displayAccountName are mandatory fields.
accounts:
  - awsAccessKey: ""
    awsSecretKey: ""
    displayAccountName: "AppD"

    # Regions where Elasticsearch service is created
    # Allowed values: Please refer to regionEndPoints configuration in this file.
    regions: ["us-west-2"]

credentialsDecryptionConfig:
  enableDecryption: "false"
  encryptionKey:

proxyConfig:
  host:
  port:
  username:
  password:

# Filters metrics based on provided Dimension values.
# Accepts comma separated values and regex patterns.
# If `values:[".*"]` is used, all are monitored,
# If `values:[]` is used, none are monitored

dimensions:
  - name: "DomainName"
    displayName: "Domain"
    values: [""]
  - name: "ClientId"
    displayName: "Client Id"
    values: [""]
  - name: "NodeId"
    displayName: "Node Id"
    values: [""]

# Detailed will fire CloudWatch API calls every 1 minute
# Basic will poll CloudWatch API every 5 min

cloudWatchMonitoring: "Basic"

#If you want any other interval ( other than the mentioned "Basic" or "Detailed" in the above configuration )
#configure it here, if not leave it empty. This value is in minutes
#cloudWatchMonitoringInterval: 0

concurrencyConfig:
  noOfAccountThreads: 3
  noOfRegionThreadsPerAccount: 3
  noOfMetricThreadsPerRegion: 3
  #Thread timeout in seconds
  threadTimeOut: 30

# Global metrics config for all accounts
metricsConfig:
  # By default, all metrics retrieved from CloudWatch are 'Average' values.
  # This option allows you to override the metric type.
  # name supports regex
  # Allowed statTypes are: ave, max, min, sum, samplecount
  # Note: Irrespective of the metric type, value will still be reported as
  # Observed value to the Controller
  includeMetrics:
    # List of metrics can be found here
    # https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-cloudwatchmetrics
    # Cluster metrics
    - name: "ClusterStatus.green"
      alias: "Cluster Status|Green"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ClusterStatus.red"
      alias: "Cluster Status|Red"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ClusterStatus.green"
      alias: "Cluster Status|Yellow"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "Nodes"
      alias: "Total Nodes (Count)"
      statType: "min"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "SearchableDocuments"
      alias: "Searchable Documents (Count)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "DeletedDocuments"
      alias: "Deleted Documents (Count)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "CPUUtilization"
      alias: "CPUUtilization (Percent)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "FreeStorageSpace"
      alias: "Total Free Storage Space (GiB)"
      statType: "sum"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ClusterUsedSpace"
      alias: "Cluster Used Space (GiB)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ClusterIndexWritesBlocked"
      alias: "Cluster Index Writes Blocked"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "JVMMemoryPressure"
      alias: "JVM Memory Pressure (Percent)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "AutomatedSnapshotFailure"
      alias: "Automated Snapshot Failure"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    # CPUCreditBalance metric is available only for the t2.micro.elasticsearch, t2.small.elasticsearch
    # and t2.medium.elasticsearch instance types.
    - name: "CPUCreditBalance"
      alias: "CPU Credit Balance"
      statType: "min"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "KibanaHealthyNodes"
      alias: "Kibana Healthy Nodes"
      statType: "min"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "KMSKeyError"
      alias: "KMS Key Error"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "KMSKeyInaccessible"
      alias: "KMS Key Inaccessible"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "InvalidHostHeaderRequests"
      alias: "Invalid Host Header Requests"
      statType: "sum"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ElasticsearchRequests"
      alias: "Elasticsearch Requests"
      statType: "sum"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "RequestCount"
      alias: "Request Count"
      statType: "sum"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    # Dedicated Master Node Metrics
    - name: "MasterCPUUtilization"
      alias: "Master CPU Utilization (Percent)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "MasterJVMMemoryPressure"
      alias: "Master JVM Memory Pressure (Percent)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    # CPUCreditBalance metric is available only for the t2.micro.elasticsearch, t2.small.elasticsearch
    # and t2.medium.elasticsearch instance types.
    - name: "MasterCPUCreditBalance"
      alias: "Master CPU Credit Balance"
      statType: "min"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "MasterReachableFromNode"
      alias: "Master Reachable From Node"
      statType: "min"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    # EBS Volume Metrics
    - name: "ReadLatency"
      alias: "Read Latency (Seconds)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "WriteLatency"
      alias: "Write Latency (Seconds)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ReadThroughput"
      alias: "Read Throughput (bytes/second)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "WriteThroughput"
      alias: "Write Throughput (bytes/second)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "DiskQueueDepth"
      alias: "Disk Queue Depth"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ReadIOPS"
      alias: "Read IOPS (operations/second)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "WriteIOPS"
      alias: "Write IOPS (operations/second)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    # Instance Metrics
    - name: "IndexingLatency"
      alias: "Indexing Latency (milliseconds)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "IndexingRate"
      alias: "Indexing Rate (operation/minute)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "SearchLatency"
      alias: "Search Latency (milliseconds)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "SearchRate"
      alias: "Search Rate (operation/minute)"
      statType: "ave"
      delta: false
      multiplier: 1
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
    - name: "SysMemoryUtilization"
      alias: "Maximum Memory Utilization (Percent)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "JVMGCYoungCollectionCount"
      alias: "Young Collection Count"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "JVMGCYoungCollectionTime"
      alias: "Young Collection Time (milliseconds)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "JVMGCOldCollectionCount"
      alias: "Old Collection Count"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "JVMGCOldCollectionTime"
      alias: "Old Collection Time (milliseconds)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolForce_mergeQueue"
      alias: "Queued Tasks in Merge Thread Pool (Count)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolForce_mergeRejected"
      alias: "Rejected Tasks in Merge Thread Pool (Count)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolForce_mergeThreads"
      alias: "Merge Thread Pool Size (Rejected + Queued Tasks)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolIndexQueue"
      alias: "Queued Tasks in Index Thread Pool (Count)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolIndexRejected"
      alias: "Rejected Tasks in Index Thread Pool (Count)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolIndexThreads"
      alias: "Index Thread Pool Size (Rejected + Queued Tasks)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolSearchQueue"
      alias: "Queued Tasks in Search Thread Pool (Count)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolSearchRejected"
      alias: "Rejected Tasks in Search Thread Pool (Count)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"
    - name: "ThreadpoolSearchThreads"
      alias: "Search Thread Pool Size (Rejected + Queued Tasks)"
      statType: "max"
      delta: false
      multiplier: 1
      aggregationType: "OBSERVATION"
      timeRollUpType: "CURRENT"
      clusterRollUpType: "INDIVIDUAL"

  metricsTimeRange:
    startTimeInMinsBeforeNow: 10
    endTimeInMinsBeforeNow: 0

  # Rate limit ( per second ) for GetMetricStatistics, default value is 400.
  # https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html
  getMetricStatisticsRateLimit: 400

  # The max number of retry attempts for failed retryable requests
  # (ex: 5xx error responses from a service) or throttling errors

  maxErrorRetrySize: 3

regionEndPoints:
  us-east-1 : monitoring.us-east-1.amazonaws.com
  us-east-2 : monitoring.us-east-2.amazonaws.com
  us-west-1 : monitoring.us-west-1.amazonaws.com
  us-west-2 : monitoring.us-west-2.amazonaws.com
  ap-northeast-1 : monitoring.ap-northeast-1.amazonaws.com
  ap-northeast-2: monitoring.ap-northeast-2.amazonaws.com
  ap-northeast-3 : monitoring.ap-northeast-3.amazonaws.com
  ap-south-1 : monitoring.ap-south-1.amazonaws.com
  ap-southeast-1 : monitoring.ap-southeast-1.amazonaws.com
  ap-southeast-2 : monitoring.ap-southeast-2.amazonaws.com
  ca-central-1 : monitoring.ca-central-1.amazonaws.com
  cn-north-1 : monitoring.cn-north-1.amazonaws.com.cn
  cn-northwest-1 : monitoring.cn-northwest-1.amazonaws.com.cn
  eu-central-1 : monitoring.eu-central-1.amazonaws.com
  eu-west-1 : monitoring.eu-west-1.amazonaws.com
  eu-west-2 : monitoring.eu-west-2.amazonaws.com
  eu-west-3 : monitoring.eu-west-3.amazonaws.com
  sa-east-1 : monitoring.sa-east-1.amazonaws.com
  us-gov-west-1 : monitoring.us-gov-west-1.amazonaws.com

# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile.
controllerInfo:
  controllerHost: "" # -Dappdynamics.controller.hostName
  controllerPort: 8090 # -Dappdynamics.controller.port
  controllerSslEnabled: false # -Dappdynamics.controller.ssl.enabled
  enableOrchestration: false # N/A
  uniqueHostId: "" # -Dappdynamics.agent.uniqueHostId
  username: "" # -Dappdynamics.agent.monitors.controller.username
  password: "" # -Dappdynamics.agent.monitors.controller.password
  encryptedPassword: "" # -Dappdynamics.agent.monitors.controller.encryptedPassword
  accountAccessKey: "" # -Dappdynamics.agent.accountAccessKey
  account: "" # -Dappdynamics.agent.accountName
  machinePath: "" # -Dappdynamics.machine.agent.hierarchyPath
  simEnabled: false # -Dappdynamics.sim.enabled
  applicationName: "" # -Dappdynamics.agent.applicationName
  tierName: "" # -Dappdynamics.agent.tierName
  nodeName: "" # -Dappdynamics.agent.nodeName

#Encryption key for your controllerInfo password
encryptionKey: "abcd"
